site_name: Fudamentos de Redes de Computadores
repo_url: https://github.com/francisco1code/FRC_docs

extra_css: 
        - assets/stylesheets/extra.css

theme:
        name: material
        language: pt
        features:
                - navigation.tabs

nav:
        - Home: index.md
        - Relatório Intranet: relatorio-intranet.md
        - Relatório Criptografia Simétrica e assimétrica: cripto.md
